=== sorgazb/DTD_Practice/EjercicioLiga/partidos.dtd
<!ELEMENT liga (partido+)>
<!ELEMENT partido (local, visitante, goleslocal, golesvisitante)>
<!ELEMENT local (#PCDATA)>
<!ELEMENT visitante (#PCDATA)>
<!ELEMENT goleslocal (#PCDATA)>
<!ELEMENT golesvisitante (#PCDATA)>

=== sorgazb/DTD_Practice/EjercicioLiga/partidos.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE liga SYSTEM "partidos.dtd">
<liga>
 <partido>
 <local>Moralo</local>
 <visitante>Talayuela</visitante>
 <goleslocal>1</goleslocal>
 <golesvisitante>0</golesvisitante>
 </partido>
 
 <partido>
 <local>Rosalejo</local>
 <visitante>Jarandilla</visitante>
 <goleslocal>1</goleslocal>
 <golesvisitante>1</golesvisitante>
 </partido>
 
 <partido>
 <local>Ti√©tar</local>
 <visitante>Millanes</visitante>
 <goleslocal>2</goleslocal>
 <golesvisitante>1</golesvisitante>
 </partido>
</liga>
