=== sorgazb/DTD_Practice/EjercicioLiga/partidos2.dtd
<!ELEMENT liga (partido+)>
<!ELEMENT partido (local, visitante)>
<!ELEMENT local (#PCDATA)>
<!ELEMENT visitante (#PCDATA)>
<!ATTLIST local goles CDATA #REQUIRED>
<!ATTLIST visitante goles CDATA #REQUIRED>

=== sorgazb/DTD_Practice/EjercicioLiga/partidos2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE liga SYSTEM "partidos2.dtd">
<liga>
 <partido>
 <local goles="1">Moralo</local>
 <visitante goles="0">Talayuela</visitante>
 </partido>
 
 <partido>
 <local goles="1">Rosalejo</local>
 <visitante goles="1">Jarandilla</visitante>
 </partido>
 
 <partido>
 <local goles="2">Ti√©tar</local>
 <visitante goles="2">Millanes</visitante>
 </partido>
</liga>
